services:
  dev:
    image: ghcr.io/dimasad/fr3-moveit-servo:latest
    privileged: true
    restart: no
    network_mode: host
    volumes:
      - .:/workspace
    environment:
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
    command: sleep infinity
